export const OPEN_MAIN_DRAWER = 'OPEN_MAIN_DRAWER';
export const CLOSE_MAIN_DRAWER = 'CLOSE_MAIN_DRAWER';

export const USER_SIGNED_UP_IN_SYSTEM = 'USER_SIGNED_UP_IN_SYSTEM';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const PERSON_ADD = 'PERSON_ADD';
export const PERSONS_INIT = "PERSONS_INIT";
export const SET_PERSONS_LOADER = "SET_PERSONS_LOADER";
